### ISSUE TITLE
Python 3.11 wheels

### ISSUE THREAD

**Issue by dstansby** [matplotlib/mplcairo#51]
A short feature request for Python 3.11 wheels to be built/uploaded 😃

**Comment by anntzer** [comment]
This is currently blocked by the tests being broken with matplotlib 3.8. I'd like to fix that first, but am very unlikely to have time to work on that any time soon.
As a stopgap I could accept a PR that just updates run-mpl-test-suite to xfail all the problematic tests and tag that as 0.5.1.

**Comment by nabobalis** [comment]
Hello @anntzer, I have a similar question for wheels for py312.

What can I do to help and try to get wheels out for that?

**Comment by anntzer** [comment]
Unfortunately, my bandwidth for working on mplcairo infrastructure is close to none these days (compiling from source should always work, and HEAD should always be in a usable state as I still use this backend for regular work).  It would be nice if a core dev of an established scientific python package could get interested in helping with the maintenance here.  (It doesn't have to be a Matplotlib core dev but I'd much rather have someone already reasonably well-established in the scientific python community, to avoid xz-style debacles.)

**Comment by nabobalis** [comment]
Hi @anntzer, sorry for forgetting to reply for several months.

I am not sure I am qualified to handle the infrastructure of the a complex C++ library and fix what is broken. I have worked with sunpy and astropy developers as well as numfocus and Scientific Python folks who could vouch for me as not being a bad agent.

**Comment by anntzer** [comment]
I am happy to believe that you are a good agent.  Even if you can't help with the build architecture, there's always the work of keeping mplcairo up to date with the latest changes in maptlotlib; as you can see the test suite currently fails due to changes in matplotlib 3.9 (I think there may even be problems going back to 3.8) and mplcairo needs to be updated accordingly.

**Comment by nabobalis** [comment]
Thanks @anntzer. I will try to work on this. 

From the outside (at least right now), it is hard for me to judge if a test change/failure is due to MPL changes or something that would need to be changed inside mplcario. If I have any questions about differences due to MPL versions, would you be willing to help?

**Comment by anntzer** [comment]
Sure.  (In practice matplotlib is quite underspecced and I tend to just follow its actual behavior on its last version.)

**Comment by anntzer** [comment]
Released mplcairo 0.6 with wheels for Python up to 3.13.
